init
FrendsPlatform/Frends.FTP pull request #4
Opened 2022-05-18 08:35 UTC by ttossavainen

2022-05-20 14:36 UTC, jefim requested changes

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +public class UnitTest1
Rename to better class and file name

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +        Assert.IsTrue(result.Result.Files.Any(x => x.Name.Contains("testfile.txt")));
Should we have a count assert or is it dynamic somehow (the amount of files). Maybe we could have a specific directory that always has X files?

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +    public void ListAllTest()
I am not sure I see a diff between this and ListAll2Test besides Filename being null vs *. Thus if this is the thing you are testing, then it is best to somehow reflect it in the method name. E.g. ListFiles_FilenameNull_ListsAllFiles and for ListAll2Test then maybe something like ListFiles_FilenameWildcardStar_ListsAllFiles. Those are just suggestions, that follow an old convention of {THIS_THAT_IS_TESTED}_{CONDITION}_{EXPECTED_RESULT}

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +    public void ListAll2Test()
Rename to better name of test

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +    /// List all files. Checking result count.
Not sure if we need those comments. We can safely disable public member comment requirements in unit tests. If unit test name is proper - I do not see why have a comment for it.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +            Path = "/TestListsubdir",
If we are using a generic FTP for all FTP tasks - maybe we should name those folders specific to tasks that are tessted? Like should this FTP folder be better names as "ListFiles_TestListSubdir"? This way we always know which dirs on FTP belong to which tests.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +            Path = "/NoFilesHere",
Same comment on dir naming as above.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +    public void ListWitPrefixTest()
Typo Wit -> With

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +            Path = "/",
This comment applies to all other places that reference "/". Is this is a generic FTP for all other tasks too, then should we avoid using root folder altogether and maybe create subfolders always for each task?..

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +    public void ListWitPrefix2Test()
Typo

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +    public void ListWitPrefix3Test()
Typo

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles.Tests/UnitTest1.cs
> +            Path = "/Pro",
Own folder for different cases, folder naming

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/Input.cs
> +        public string User { get; set; }
Lets do Username, as I think in a lot of other places we also use Username and not User

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/Input.cs
> +        public int Port { get; set; }
Should we have a default value?

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/Input.cs
> +        /// Filename. The file mask uses regular expressions, but for convenience, it has special handling for * and ? wildcards. Use * or leave empty to list all files.
Can we have a more extensive explanation, including regexes

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/Result.cs
> +        internal Result(List<ListObject> listObject)
I do not mind really, but you could omit the constructor altogether and use the initializer syntax like `return new Result { Files = something };` Just as a suggestion :)

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/Result.cs
> +        public List<ListObject> Files { get; set; }
Make setter private (or internal if planning on using object initializer from the comment below about ctor).

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +        /// <example>3.5.2022 0.00.00</example>
Can we have a better example, please. Lets put it in ISO 8601, which is standard internationally (e.g. 2022-05-20T13:21:42Z).

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +        public DateTime Modified { get; set; }
Lets rename to LastModified

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +        /// <example>/testfile.txt</example>
Lets do an example with a subdirectory to show a slightly more extended example.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +        /// File size.
Please specify what is the unit - bytes, kilobytes, megabytes etc

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +	    public long Size { get; set; }
Actually, it would be also nice to have the unit in property name. Like SizeBytes instead of just Size.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +        public bool Success { get; set; }
I do not understand why is this Success at this level - this class is for indivisual files, not for overall status. Or am I missing something?

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +        public bool Success { get; set; }
Overall, I do not think that we need this property anyway in the whole task. It just lists files and if none are found you can see this from the result when it does not contain anything.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Frends - Backup.FTP.ListFiles.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
What is this file?

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Frends.FTP.ListFiles.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
Just curious - where do we use this AspNetCore library in this task?

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +        /// <returns>List { DateTime Modified, string Name, string FullPath, long Size, bool Success }</returns>
Do not forget to update this when you have updated the result class.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +            if (!string.IsNullOrWhiteSpace(input.User) && string.IsNullOrWhiteSpace(input.Password) || string.IsNullOrWhiteSpace(input.User) && !string.IsNullOrWhiteSpace(input.Password)) throw new E
Can we split this if into multiple ones (at the OR part) since this is way too confusing to comprehend as a reader.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +                if (result.Count < 1) { result.Add(new ListObject { Success = false }); };
As previously noted - no need for this, just return an empty list and remove the success property altogether.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +                if (ex.Message.Contains("Cannot determine the frame size or a corrupted frame was received.") && string.IsNullOrWhiteSpace(input.User))
Can you briefly explain why this is necessary and overall why do we check for this?.. I am confused. And also, if this is really needed - it is very useful to leave a comment in code explaining why this is in here, since this is definitely not a self-explanatory way to handle errors.

2022-05-20 14:36 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +                    throw new Exception(ex.ToString());
This is not a good way to wrap an exception. Essentially you are creating a new exception and only taking a small portion of info along (ignoring the stack trace and inner exceptions, if any are present). Instead the correct way of wrapping an exception is something like this:
`new Exception("Error doing action XYZ, check inner exception for details", ex)`
In this example you set ex as the inner exception into your new exception and all information is retained.

2022-05-23 11:00 UTC, ttossavainen commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Frends - Backup.FTP.ListFiles.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Sometimes VStudio likes to create these and I don't notice them before pushing.

2022-05-23 11:09 UTC, ttossavainen commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Frends.FTP.ListFiles.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
It seems that nowhere and it came with the template. Removed, rebuilded and unit tested without problems.

2022-05-23 11:31 UTC, ttossavainen commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +                if (ex.Message.Contains("Cannot determine the frame size or a corrupted frame was received.") && string.IsNullOrWhiteSpace(input.User))
This uninformative (in my opinion) error message is from the endpoint and one way to cause this is to use incorrect credentials. The idea of this exception is to guide end-user to check their credentials before creating a support ticket.

2022-06-03 06:18 UTC, jefim commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +        /// <returns>List { ListObject }</returns>
Can you convert it back to previous way that has the actual properties of ListObject?

2022-06-20 08:58 UTC, Svenskapojkarna commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/Input.cs
> +namespace Frends.FTP.ListFiles.Definitions
Please use one-line namespace definition.

2022-06-20 08:58 UTC, Svenskapojkarna commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/ListObject.cs
> +namespace Frends.FTP.ListFiles.Definitions
Please use one-line namespace definition.

2022-06-20 08:58 UTC, Svenskapojkarna commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Definitions/Result.cs
> +namespace Frends.FTP.ListFiles.Definitions
Please use one-line namespace definition.

2022-06-20 08:58 UTC, Svenskapojkarna commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/Frends - Backup.FTP.ListFiles.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Please delete this file.

2022-06-20 08:58 UTC, Svenskapojkarna commented on Frends.FTP.ListFiles/Frends.FTP.ListFiles/ListFiles.cs
> +namespace Frends.FTP.ListFiles
Please use one-line namespace definition.

2022-06-21 06:07 UTC, merged